[package]
name = "scanflow"
version = "0.3.0"
authors = ["Aurimas Blažulionis <0x60@pm.me>"]
edition = "2021"
license = "MIT"
description = "memory scanning library based on memflow"
documentation = "https://docs.rs/scanflow"
categories = ["parsing", "os", "memory-management"]
keywords = ["scanflow", "memflow", "cheatengine", "memory", "dma"]
repository = "https://github.com/h33p/scanflow"
readme = "../README.md"

[dependencies]
memflow = "0.2"
iced-x86 = "1.21"
pbr = { version = "1.1", optional = true }
rayon = "1.10"
rayon-tlsctx = "0.2"
memchr = "2.8"

[features]
default = []
progress_bar = ["pbr"]

[dev-dependencies]
memflow = { version = "0.2", features = ["dummy_mem"] }